### ISSUE TITLE
Your book

### ISSUE THREAD

**Issue by fzeeshan** [nfrankel/Learning-Vaadin#1]
Hi I just purchased your book, I am trying to work on SQL Container, unfortunately there isn't any example that I could download from your github account. Do you have any suggestions for me?
thanks

**Comment by nfrankel** [comment]
Hello
SQLContainer addon is now part of the regular library but I found this project that might help you https://dev.vaadin.com/svn/addons/SQLContainer/tags/1.0.0-pre2/
